name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      ENCRYPTION_KEY: ${{ secrets.TEST_ENCRYPTION_KEY }}
      JWT_KEY: ${{ secrets.JWT_KEY }}
      JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
      JWT_AUDIENCE: ${{ secrets.JWT_AUDIENCE }}
      EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_NAME: ${{ secrets.EMAIL_NAME }}
      POSTGRES_CONNECTION_STRING: ${{ secrets.POSTGRES_CONNECTION_STRING }}
      REDIS_CONNECTION_STRING: ${{ secrets.REDIS_CONNECTION_STRING }}
      MONGODB_CONNECTION_STRING: ${{ secrets.MONGODB_CONNECTION_STRING }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore
        run: dotnet restore tests/tests.csproj

      - name: Build
        run: dotnet build tests/tests.csproj --no-restore

      - name: Test
        run: dotnet test tests/tests.csproj --no-build --verbosity normal
